#!/bin/sh

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "main" ] || [ "$branch" = "master" ]; then
  echo "❌ ERRO: Você está tentando commitar na branch '$branch'."
  echo "Crie uma nova branch antes de prosseguir: git checkout -b nome-da-branch"
  exit 1
fi

exit 0